[target.thumbv7em-none-eabihf]
# runner = "gdb-multiarch -q -x openocd.gdb" # linux
runner = "arm-none-eabi-gdb -q -x openocd.gdb" # macos

rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"
